In [1]:
import pandas as pd 

dft2=pd.read_csv("dft.csv") 
dft2.head()

AlertTitle            Category   IncidentGrade        EntityType  \
0           5       InitialAccess   FalsePositive              User   
1         270    CredentialAccess    TruePositive              User   
2          13        Exfiltration  BenignPositive       MailMessage   
3           4  SuspiciousActivity    TruePositive           Machine   
4         153    CredentialAccess    TruePositive  CloudApplication   

  EvidenceRole  DeviceId  Sha256  IpAddress     Url  AccountSid  ...  \
0     Impacted     98799  138268     360606  160396       12578  ...   
1     Impacted     98799  138268     360606  160396      145718  ...   
2     Impacted     98799  138268     360606  160396      441377  ...   
3     Impacted        21  138268     360606  160396      441377  ...   
4     Impacted     98799  138268     360606  160396      441377  ...   

   ApplicationName  OAuthApplicationId  FileName  FolderPath  ResourceIdName  \
0             3421                 881    289573      117668            3586   
1             3421                 881    289573      117668            3586   
2             3421                 881    289573      117668            3586   
3             3421                 881    289573      117668            3586   
4                1                 881    289573      117668            3586   

   OSFamily  OSVersion  CountryCode  State   City  
0   Unknown         66          242   1445  10630  
1   Unknown         66          242   1445  10630  
2   Unknown         66          242   1445  10630  
3   Unknown         66          242   1445  10630  
4   Unknown         66          242   1445  10630  

[5 rows x 28 columns]

In [3]:
dft2.drop(columns=["OAuthApplicationId","RegistryValueName", "RegistryValueData","OSFamily","ResourceIdName","Url","OSVersion",  "RegistryKey", "ApplicationId","EvidenceRole","ApplicationName"],inplace=True)

In [5]:
dft2.shape

(1500000, 17)

In [7]:
dft2.head()

AlertTitle            Category   IncidentGrade        EntityType  DeviceId  \
0           5       InitialAccess   FalsePositive              User     98799   
1         270    CredentialAccess    TruePositive              User     98799   
2          13        Exfiltration  BenignPositive       MailMessage     98799   
3           4  SuspiciousActivity    TruePositive           Machine        21   
4         153    CredentialAccess    TruePositive  CloudApplication     98799   

   Sha256  IpAddress  AccountSid  AccountUpn  AccountObjectId  AccountName  \
0  138268     360606       12578       15470            12705        13834   
1  138268     360606      145718      216432           148042       139254   
2  138268     360606      441377        5721           425863       453297   
3  138268     360606      441377      673934           425863       453297   
4  138268     360606      441377      673934           425863       453297   

   DeviceName  FileName  FolderPath  CountryCode  State   City  
0      153085    289573      117668          242   1445  10630  
1      153085    289573      117668          242   1445  10630  
2      153085    289573      117668          242   1445  10630  
3          26    289573      117668          242   1445  10630  
4      153085    289573      117668          242   1445  10630

In [9]:
import pandas as pd 

cols=[col for col in dft2.columns if col!="IncidentGrade"]
cols.append("IncidentGrade") 

dft2=dft2[cols] 
dft2

AlertTitle            Category        EntityType  DeviceId  Sha256  \
0                 5       InitialAccess              User     98799  138268   
1               270    CredentialAccess              User     98799  138268   
2                13        Exfiltration       MailMessage     98799  138268   
3                 4  SuspiciousActivity           Machine        21  138268   
4               153    CredentialAccess  CloudApplication     98799  138268   
...             ...                 ...               ...       ...     ...   
1499995         452    CredentialAccess           Process     98799       2   
1499996           5       InitialAccess                Ip     98799  138268   
1499997           0       InitialAccess                Ip     98799  138268   
1499998           0       InitialAccess                Ip     98799  138268   
1499999           1       InitialAccess           Mailbox     98799  138268   

         IpAddress  AccountSid  AccountUpn  AccountObjectId  AccountName  \
0           360606       12578       15470            12705        13834   
1           360606      145718      216432           148042       139254   
2           360606      441377        5721           425863       453297   
3           360606      441377      673934           425863       453297   
4           360606      441377      673934           425863       453297   
...            ...         ...         ...              ...          ...   
1499995     360606      441377      673934           425863       453297   
1499996      26297      441377      673934           425863       453297   
1499997        377      441377      673934           425863       453297   
1499998     244298      441377      673934           425863       453297   
1499999     360606        4145        5233             4129         4434   

         DeviceName  FileName  FolderPath  CountryCode  State   City  \
0            153085    289573      117668          242   1445  10630   
1            153085    289573      117668          242   1445  10630   
2            153085    289573      117668          242   1445  10630   
3                26    289573      117668          242   1445  10630   
4            153085    289573      117668          242   1445  10630   
...             ...       ...         ...          ...    ...    ...   
1499995      153085         1           1          242   1445  10630   
1499996      153085    289573      117668          242   1445  10630   
1499997      153085    289573      117668            1      0      0   
1499998      153085    289573      117668           17    229   8150   
1499999      153085    289573      117668          242   1445  10630   

          IncidentGrade  
0         FalsePositive  
1          TruePositive  
2        BenignPositive  
3          TruePositive  
4          TruePositive  
...                 ...  
1499995    TruePositive  
1499996  BenignPositive  
1499997    TruePositive  
1499998   FalsePositive  
1499999    TruePositive  

[1500000 rows x 17 columns]

In [11]:
dft2.to_csv("dft2.csv",index=False)

In [12]:
import pandas as pd 

dft3=pd.read_csv("dft2.csv") 
dft3.head()

AlertTitle            Category        EntityType  DeviceId  Sha256  \
0           5       InitialAccess              User     98799  138268   
1         270    CredentialAccess              User     98799  138268   
2          13        Exfiltration       MailMessage     98799  138268   
3           4  SuspiciousActivity           Machine        21  138268   
4         153    CredentialAccess  CloudApplication     98799  138268   

   IpAddress  AccountSid  AccountUpn  AccountObjectId  AccountName  \
0     360606       12578       15470            12705        13834   
1     360606      145718      216432           148042       139254   
2     360606      441377        5721           425863       453297   
3     360606      441377      673934           425863       453297   
4     360606      441377      673934           425863       453297   

   DeviceName  FileName  FolderPath  CountryCode  State   City   IncidentGrade  
0      153085    289573      117668          242   1445  10630   FalsePositive  
1      153085    289573      117668          242   1445  10630    TruePositive  
2      153085    289573      117668          242   1445  10630  BenignPositive  
3          26    289573      117668          242   1445  10630    TruePositive  
4      153085    289573      117668          242   1445  10630    TruePositive

In [15]:
from sklearn.preprocessing import LabelEncoder 

le=LabelEncoder() 

dft3["IncidentGrade"]=le.fit_transform(dft3["IncidentGrade"])
dft3.head()

AlertTitle            Category        EntityType  DeviceId  Sha256  \
0           5       InitialAccess              User     98799  138268   
1         270    CredentialAccess              User     98799  138268   
2          13        Exfiltration       MailMessage     98799  138268   
3           4  SuspiciousActivity           Machine        21  138268   
4         153    CredentialAccess  CloudApplication     98799  138268   

   IpAddress  AccountSid  AccountUpn  AccountObjectId  AccountName  \
0     360606       12578       15470            12705        13834   
1     360606      145718      216432           148042       139254   
2     360606      441377        5721           425863       453297   
3     360606      441377      673934           425863       453297   
4     360606      441377      673934           425863       453297   

   DeviceName  FileName  FolderPath  CountryCode  State   City  IncidentGrade  
0      153085    289573      117668          242   1445  10630              1  
1      153085    289573      117668          242   1445  10630              2  
2      153085    289573      117668          242   1445  10630              0  
3          26    289573      117668          242   1445  10630              2  
4      153085    289573      117668          242   1445  10630              2

In [17]:
dft3.shape

(1500000, 17)

In [19]:
dft3.head()

AlertTitle            Category        EntityType  DeviceId  Sha256  \
0           5       InitialAccess              User     98799  138268   
1         270    CredentialAccess              User     98799  138268   
2          13        Exfiltration       MailMessage     98799  138268   
3           4  SuspiciousActivity           Machine        21  138268   
4         153    CredentialAccess  CloudApplication     98799  138268   

   IpAddress  AccountSid  AccountUpn  AccountObjectId  AccountName  \
0     360606       12578       15470            12705        13834   
1     360606      145718      216432           148042       139254   
2     360606      441377        5721           425863       453297   
3     360606      441377      673934           425863       453297   
4     360606      441377      673934           425863       453297   

   DeviceName  FileName  FolderPath  CountryCode  State   City  IncidentGrade  
0      153085    289573      117668          242   1445  10630              1  
1      153085    289573      117668          242   1445  10630              2  
2      153085    289573      117668          242   1445  10630              0  
3          26    289573      117668          242   1445  10630              2  
4      153085    289573      117668          242   1445  10630              2

In [21]:
import pandas as pd


columns_to_encode = [
    'AlertTitle', 'Category', 'EntityType', 'DeviceId', 'Sha256', 'IpAddress', 
    'AccountSid', 'AccountUpn', 'AccountObjectId', 'AccountName', 'DeviceName', 
    'FileName', 'FolderPath', 'CountryCode', 'State', 'City'
]


for column in columns_to_encode:
    column_mean = dft3.groupby(column)['IncidentGrade'].mean()
    
    
    dft3[column] = dft3[column].map(column_mean).round(3)


dft3.head()

AlertTitle  Category  EntityType  DeviceId  Sha256  IpAddress  AccountSid  \
0       0.852     1.301       1.102     1.012   1.031      0.942       1.000   
1       1.717     1.036       1.102     1.012   1.031      0.942       2.000   
2       0.000     0.509       0.651     1.012   1.031      0.942       0.971   
3       0.890     0.947       0.709     2.000   1.031      0.942       0.971   
4       0.865     1.036       1.007     1.012   1.031      0.942       0.971   

   AccountUpn  AccountObjectId  AccountName  DeviceName  FileName  FolderPath  \
0       1.000            1.000        1.000       1.025     1.043       1.039   
1       2.000            2.000        2.000       1.025     1.043       1.039   
2       0.000            0.971        0.979       1.025     1.043       1.039   
3       1.034            0.971        0.979       2.000     1.043       1.039   
4       1.034            0.971        0.979       1.025     1.043       1.039   

   CountryCode  State   City  IncidentGrade  
0        0.934  0.945  0.945              1  
1        0.934  0.945  0.945              2  
2        0.934  0.945  0.945              0  
3        0.934  0.945  0.945              2  
4        0.934  0.945  0.945              2

In [23]:
dft3.to_csv("dft3.csv",index=False)

In [1]:
import pandas as pd 

dft4=pd.read_csv("dft3.csv") 
dft4.head()

AlertTitle  Category  EntityType  DeviceId  Sha256  IpAddress  AccountSid  \
0       0.852     1.301       1.102     1.012   1.031      0.942       1.000   
1       1.717     1.036       1.102     1.012   1.031      0.942       2.000   
2       0.000     0.509       0.651     1.012   1.031      0.942       0.971   
3       0.890     0.947       0.709     2.000   1.031      0.942       0.971   
4       0.865     1.036       1.007     1.012   1.031      0.942       0.971   

   AccountUpn  AccountObjectId  AccountName  DeviceName  FileName  FolderPath  \
0       1.000            1.000        1.000       1.025     1.043       1.039   
1       2.000            2.000        2.000       1.025     1.043       1.039   
2       0.000            0.971        0.979       1.025     1.043       1.039   
3       1.034            0.971        0.979       2.000     1.043       1.039   
4       1.034            0.971        0.979       1.025     1.043       1.039   

   CountryCode  State   City  IncidentGrade  
0        0.934  0.945  0.945              1  
1        0.934  0.945  0.945              2  
2        0.934  0.945  0.945              0  
3        0.934  0.945  0.945              2  
4        0.934  0.945  0.945              2

In [ ]:
                                          #DECISION TREE

In [27]:
                               #TRIAL AND ERROR METHOD TO FIND BEST MAX_DEPTH 

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report  



X=dft4.drop(columns=["IncidentGrade"]) 
y=dft4["IncidentGrade"] 

X_train,X_val,y_train,y_val=train_test_split(X,y,test_size=0.2,random_state=42) 

max_depth_values = [5, 10, 15, 20]
min_samples_split_values = [2, 5, 10]
min_samples_leaf_values = [1, 2, 5]
criterion_values = ['gini', 'entropy'] 

best_accuracy=0 
best_params={} 

for max_depth in max_depth_values:
    for min_samples_split in min_samples_split_values:
        for min_samples_leaf in min_samples_leaf_values:
            for criterion in criterion_values:
                clf=DecisionTreeClassifier(max_depth=max_depth,
                                           min_samples_split=min_samples_split,
                                           min_samples_leaf=min_samples_leaf,
                                           criterion=criterion,
                                           random_state=42) 
                clf.fit(X_train,y_train)
                y_pred=clf.predict(X_val) 
                accuracy=accuracy_score(y_pred,y_val) 
                if accuracy>best_accuracy:
                    best_accuracy=accuracy
                    best_params={
                        'max_depth':max_depth,
                        'min_samples_split':min_samples_split,
                        'min_samples_leaf':min_samples_leaf,
                        'criterion':criterion 
                    } 

print("Best Accuracy:",best_accuracy) 
print("Best_params:",best_params)


Best Accuracy: 0.89249
Best_params: {'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 1, 'criterion': 'entropy'}


In [3]:
                                    #DECISION TREE CLASSIFICATION 

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report 

X=dft4.drop(columns=["IncidentGrade"]) 
y=dft4["IncidentGrade"]  

X_train,X_val,y_train,y_val=train_test_split(X,y,test_size=0.3,random_state=42) 


model_tree=DecisionTreeClassifier(max_depth=20,random_state=42) 


model_tree.fit(X_train,y_train) 

y_pred=model_tree.predict(X_val) 

print("Accuracy: ", accuracy_score(y_val, y_pred))
print("Confusion Matrix: \n", confusion_matrix(y_val, y_pred))
print("Classification Report: \n", classification_report(y_val, y_pred))


Accuracy:  0.8915555555555555
Confusion Matrix: 
 [[141146   6520   2141]
 [  9884 130892   9188]
 [ 10914  10153 129162]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.87      0.94      0.91    149807
           1       0.89      0.87      0.88    149964
           2       0.92      0.86      0.89    150229

    accuracy                           0.89    450000
   macro avg       0.89      0.89      0.89    450000
weighted avg       0.89      0.89      0.89    450000



In [ ]:
                                       #RANDOM FOREST CLASSIFICATION

In [7]:
                                            #TRIAL AND ERROR METHOD

from sklearn.ensemble import RandomForestClassifier 
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report 
from sklearn.model_selection import train_test_split

X=dft4.drop(columns=["IncidentGrade"]) 
y=dft4["IncidentGrade"]  

X_train,X_val,y_train,y_val=train_test_split(X,y,test_size=0.3,random_state=42) 

n_estimators_values = [100, 200] 

results={} 

for n in n_estimators_values:
    rf_model=RandomForestClassifier(n_estimators=n,random_state=42) 
    rf_model.fit(X_train,y_train)
    y_pred=rf_model.predict(X_val) 
    accuracy=accuracy_score(y_val,y_pred) 
    results[n]=accuracy
    print(f"Accuracy for n_estimators={n}: {accuracy * 100:.2f}")  

best_n_estimators = max(results, key=results.get)
print(f"Best n_estimators value: {best_n_estimators}")


Accuracy for n_estimators=100: 89.32
Accuracy for n_estimators=200: 89.32
Best n_estimators value: 200


In [9]:
                                    #RANDOMFORESTCLASSIFICATION


from sklearn.ensemble import RandomForestClassifier 
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report 
from sklearn.model_selection import train_test_split

X=dft4.drop(columns=["IncidentGrade"]) 
y=dft4["IncidentGrade"]  

X_train,X_val,y_train,y_val=train_test_split(X,y,test_size=0.3,random_state=42) 


model_rf=RandomForestClassifier(n_estimators=100, random_state=42) 

model_rf.fit(X_train,y_train)

y_pred=model_rf.predict(X_val) 

print("Accuracy: ", accuracy_score(y_val, y_pred))
print("Confusion Matrix: \n", confusion_matrix(y_val, y_pred))
print("Classification Report: \n", classification_report(y_val, y_pred))


Accuracy:  0.8931533333333334
Confusion Matrix: 
 [[140973   6584   2250]
 [  9225 131700   9039]
 [ 10976  10007 129246]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.87      0.94      0.91    149807
           1       0.89      0.88      0.88    149964
           2       0.92      0.86      0.89    150229

    accuracy                           0.89    450000
   macro avg       0.89      0.89      0.89    450000
weighted avg       0.89      0.89      0.89    450000



In [27]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import numpy as np

param_dist = {
    'max_depth': [None, 10, 20],  
    'min_samples_split': [2, 5], 
    'min_samples_leaf': [1, 2],    
    'max_features': ['sqrt', 'log2']  
}
random_search = RandomizedSearchCV(estimator=model_rf, param_distributions=param_dist, 
                                   n_iter=5, scoring='accuracy', cv=2, verbose=2, n_jobs=-1, random_state=42)

random_search.fit(X_train, y_train)

print(f"Best hyperparameters: {random_search.best_params_}")

best_rf_model = random_search.best_estimator_

y_pred_best = best_rf_model.predict(X_val)

print(f"Final Model Test Accuracy: {accuracy_score(y_val, y_pred_best)}")
print("Confusion Matrix: \n", confusion_matrix(y_val, y_pred_best))
print("Classification Report: \n", classification_report(y_val, y_pred_best))

Fitting 2 folds for each of 5 candidates, totalling 10 fits
Best hyperparameters: {'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': None}
Final Model Test Accuracy: 0.89353
Confusion Matrix: 
 [[94034  4395  1508]
 [ 6104 87839  6015]
 [ 7284  6635 86186]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.88      0.94      0.91     99937
           1       0.89      0.88      0.88     99958
           2       0.92      0.86      0.89    100105

    accuracy                           0.89    300000
   macro avg       0.89      0.89      0.89    300000
weighted avg       0.89      0.89      0.89    300000



In [29]:
train_predictions = best_rf_model.predict(X_train)
validation_predictions = best_rf_model.predict(X_val)

train_accuracy = accuracy_score(y_train, train_predictions)
validation_accuracy = accuracy_score(y_val, validation_predictions)

print(f"Training Accuracy: {train_accuracy}")
print(f"Validation Accuracy: {validation_accuracy}")

Training Accuracy: 0.9014675
Validation Accuracy: 0.89353


In [31]:
import joblib 
joblib.dump(best_rf_model,'best_model_rf.pkl')

['best_model_rf.pkl']

In [ ]:
                                               XG BOOST

In [11]:
!pip install xgboost

In [15]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score 

X=dft4.drop(columns=["IncidentGrade"]) 
y=dft4["IncidentGrade"]  

X_train,X_val,y_train,y_val=train_test_split(X,y,test_size=0.2,random_state=42) 

model1 = xgb.XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, subsample=0.8, colsample_bytree=0.8)
model1.fit(X_train, y_train)
y_pred1 = model1.predict(X_val)
accuracy1 = accuracy_score(y_val, y_pred1)
print(f"Trial 1 Accuracy: {accuracy1}")

model2 = xgb.XGBClassifier(n_estimators=200, learning_rate=0.05, max_depth=5, subsample=0.9, colsample_bytree=0.9)
model2.fit(X_train, y_train)
y_pred2 = model2.predict(X_val)
accuracy2 = accuracy_score(y_val, y_pred2)
print(f"Trial 2 Accuracy: {accuracy2}")

model3 = xgb.XGBClassifier(n_estimators=300, learning_rate=0.01, max_depth=7, subsample=1.0, colsample_bytree=1.0)
model3.fit(X_train, y_train)
y_pred3 = model3.predict(X_val)
accuracy3 = accuracy_score(y_val, y_pred3)
print(f"Trial 3 Accuracy: {accuracy3}")



Trial 1 Accuracy: 0.88351
Trial 2 Accuracy: 0.88948
Trial 3 Accuracy: 0.8870733333333334


In [19]:
                                                   #XG BOOST

import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report  

X=dft4.drop(columns=["IncidentGrade"]) 
y=dft4["IncidentGrade"]  

X_train,X_val,y_train,y_val=train_test_split(X,y,test_size=0.2,random_state=42) 


model_xgb=xgb.XGBClassifier(n_estimators=200, learning_rate=0.05, max_depth=5, subsample=0.9, colsample_bytree=0.9) 

model_xgb.fit(X_train,y_train) 

y_pred=model_xgb.predict(X_val) 

print("Accuracy Score:",accuracy_score(y_val,y_pred)) 
print("Classification report: \n",classification_report(y_val,y_pred)) 
print("Confusion Matrix: \n",confusion_matrix(y_val,y_pred))



Accuracy Score: 0.88948
Classification report: 
               precision    recall  f1-score   support

           0       0.87      0.94      0.90     99937
           1       0.91      0.83      0.87     99958
           2       0.89      0.89      0.89    100105

    accuracy                           0.89    300000
   macro avg       0.89      0.89      0.89    300000
weighted avg       0.89      0.89      0.89    300000

Confusion Matrix: 
 [[94275  4566  1096]
 [ 7130 83396  9432]
 [ 7470  3462 89173]]


In [ ]:
                                               ADA-BOOST

In [21]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


X=dft4.drop(columns=["IncidentGrade"]) 
y=dft4["IncidentGrade"]  

X_train,X_val,y_train,y_val=train_test_split(X,y,test_size=0.2,random_state=42) 

model1 = AdaBoostClassifier(n_estimators=100, learning_rate=0.01, random_state=42,algorithm='SAMME')
model1.fit(X_train, y_train)
y_pred1 = model1.predict(X_val)
accuracy1 = accuracy_score(y_val, y_pred1)
print(f"Trial 1 Accuracy: {accuracy1}")

model2 = AdaBoostClassifier(n_estimators=200, learning_rate=0.1, random_state=42,algorithm='SAMME')
model2.fit(X_train, y_train)
y_pred2 = model2.predict(X_val)
accuracy2 = accuracy_score(y_val, y_pred2)
print(f"Trial 2 Accuracy: {accuracy2}")

model3 = AdaBoostClassifier(n_estimators=300, learning_rate=0.5, random_state=42,algorithm='SAMME')
model3.fit(X_train, y_train)
y_pred3 = model3.predict(X_val)
accuracy3 = accuracy_score(y_val, y_pred3)
print(f"Trial 3 Accuracy: {accuracy3}")


Trial 1 Accuracy: 0.5745333333333333
Trial 2 Accuracy: 0.78551
Trial 3 Accuracy: 0.85967


In [25]:
                                         #ADA BOOST

from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score  

X=dft4.drop(columns=["IncidentGrade"]) 
y=dft4["IncidentGrade"]  

X_train,X_val,y_train,y_val=train_test_split(X,y,test_size=0.2,random_state=42) 


model_ad=AdaBoostClassifier(n_estimators=300,learning_rate=0.5,random_state=42,algorithm='SAMME')

model_ad.fit(X_train,y_train) 

y_pred=model_ad.predict(X_val) 

print("Accuracy: \n",accuracy_score(y_val,y_pred))
print("Classification report: \n",classification_report(y_val,y_pred)) 
print("Confusion Matrix: \n",confusion_matrix(y_val,y_pred))


Accuracy: 
 0.85967
Classification report: 
               precision    recall  f1-score   support

           0       0.92      0.86      0.89     99937
           1       0.78      0.85      0.82     99958
           2       0.89      0.87      0.88    100105

    accuracy                           0.86    300000
   macro avg       0.86      0.86      0.86    300000
weighted avg       0.86      0.86      0.86    300000

Confusion Matrix: 
 [[85749 13113  1075]
 [ 4879 85175  9904]
 [ 2403 10725 86977]]


In [ ]:
Best Model for Accuracy: Random Forest with an accuracy of 0.8932, 
which is slightly higher than Decision Tree and XGBoost. 

Best Model for Precision: Random Forest and Decision Tree have the highest precision for class 2, whereas XGBoost does well for class 1. However, AdaBoost has a much lower precision for class 1, indicating poorer performance on that class.

Best Model for Recall: Decision Tree and Random Forest have the highest recall for class 0 (94%) and for class 1, while XGBoost performs well with recall for class 2

Best Model for F1-Score: Decision Tree and Random Forest have the highest F1-scores, especially for class 0 and class 1.

Confusion Matrix Analysis:

Decision Tree:

The Decision Tree model performs fairly well with the most accurate prediction for class 0 (True Positives: 141,146) but makes a higher number of false positives for class 2 (6,520).
A significant number of false negatives for class 1 and class 2 indicate room for improvement in those categories.
Random Forest:

Random Forest shows similar performance, with slightly more accurate predictions for class 0 and class 2. The misclassifications are quite balanced across classes.
The false positives and false negatives are fairly evenly distributed compared to Decision Tree, which may suggest Random Forest’s more balanced approach in handling the classes.
XGBoost:

XGBoost demonstrates a good number of true positives for class 0 (94%) but shows some issues with class 1, where it struggles with false positives (7,130).
The misclassifications are slightly higher for class 1 compared to Decision Tree and Random Forest.
AdaBoost:

AdaBoost performs the worst in terms of accuracy and precision, especially for class 1, where it struggles (false positives: 4,879).
The confusion matrix shows significant misclassification for class 0, with 13,113 false positives.




In [ ]:
Best Model: Random Forest
Reason: It outperforms the other models with the highest accuracy (0.8932) and has the best overall balance of precision, recall, and F1-score across the classes. It also handles misclassifications well compared to the others.

So, Random Forest is your best-performing model, and it shows a strong ability to classify the cybersecurity incidents accurately across all classes.
