In [1]:
import pandas as pd 

dft2=pd.read_csv("dft1.csv") 
dft2.head()

Category   IncidentGrade        EntityType  DeviceId  IpAddress  \
0       InitialAccess   FalsePositive              User     98799     360606   
1    CredentialAccess    TruePositive              User     98799     360606   
2        Exfiltration  BenignPositive       MailMessage     98799     360606   
3  SuspiciousActivity    TruePositive           Machine        21     360606   
4    CredentialAccess    TruePositive  CloudApplication     98799     360606   

      Url  AccountSid  AccountName  DeviceName  RegistryKey  ApplicationId  \
0  160396       12578        13834      153085         1631           2251   
1  160396      145718       139254      153085         1631           2251   
2  160396      441377       453297      153085         1631           2251   
3  160396      441377       453297          26         1631           2251   
4  160396      441377       453297      153085         1631              1   

   ApplicationName  FileName  FolderPath OSFamily  CountryCode  hour  day  \
0             3421    289573      117668  Unknown          242    14   13   
1             3421    289573      117668  Unknown          242    19   12   
2             3421    289573      117668  Unknown          242    19    6   
3             3421    289573      117668  Unknown          242    23    2   
4                1    289573      117668  Unknown          242     1   12   

   month  weekday  
0      6        3  
1      6        2  
2      6        3  
3      6        6  
4      6        2

In [3]:
dft2.columns

Index(['Category', 'IncidentGrade', 'EntityType', 'DeviceId', 'IpAddress',
       'Url', 'AccountSid', 'AccountName', 'DeviceName', 'RegistryKey',
       'ApplicationId', 'ApplicationName', 'FileName', 'FolderPath',
       'OSFamily', 'CountryCode', 'hour', 'day', 'month', 'weekday'],
      dtype='object')

In [5]:
dft2.drop(columns=["ApplicationName","ApplicationId","RegistryKey","OSFamily"],inplace=True)

In [7]:
dft2.head()

Category   IncidentGrade        EntityType  DeviceId  IpAddress  \
0       InitialAccess   FalsePositive              User     98799     360606   
1    CredentialAccess    TruePositive              User     98799     360606   
2        Exfiltration  BenignPositive       MailMessage     98799     360606   
3  SuspiciousActivity    TruePositive           Machine        21     360606   
4    CredentialAccess    TruePositive  CloudApplication     98799     360606   

      Url  AccountSid  AccountName  DeviceName  FileName  FolderPath  \
0  160396       12578        13834      153085    289573      117668   
1  160396      145718       139254      153085    289573      117668   
2  160396      441377       453297      153085    289573      117668   
3  160396      441377       453297          26    289573      117668   
4  160396      441377       453297      153085    289573      117668   

   CountryCode  hour  day  month  weekday  
0          242    14   13      6        3  
1          242    19   12      6        2  
2          242    19    6      6        3  
3          242    23    2      6        6  
4          242     1   12      6        2

In [9]:
dft2.dtypes

Category         object
IncidentGrade    object
EntityType       object
DeviceId          int64
IpAddress         int64
Url               int64
AccountSid        int64
AccountName       int64
DeviceName        int64
FileName          int64
FolderPath        int64
CountryCode       int64
hour              int64
day               int64
month             int64
weekday           int64
dtype: object

In [11]:
import pandas as pd 

cols=[col for col in dft2.columns if col!="IncidentGrade"]
cols.append("IncidentGrade") 

dft2=dft2[cols] 
dft2

Category        EntityType  DeviceId  IpAddress     Url  \
0             InitialAccess              User     98799     360606  160396   
1          CredentialAccess              User     98799     360606  160396   
2              Exfiltration       MailMessage     98799     360606  160396   
3        SuspiciousActivity           Machine        21     360606  160396   
4          CredentialAccess  CloudApplication     98799     360606  160396   
...                     ...               ...       ...        ...     ...   
1499995    CredentialAccess           Process     98799     360606  160396   
1499996       InitialAccess                Ip     98799      26297  160396   
1499997       InitialAccess                Ip     98799        377  160396   
1499998       InitialAccess                Ip     98799     244298  160396   
1499999       InitialAccess           Mailbox     98799     360606  160396   

         AccountSid  AccountName  DeviceName  FileName  FolderPath  \
0             12578        13834      153085    289573      117668   
1            145718       139254      153085    289573      117668   
2            441377       453297      153085    289573      117668   
3            441377       453297          26    289573      117668   
4            441377       453297      153085    289573      117668   
...             ...          ...         ...       ...         ...   
1499995      441377       453297      153085         1           1   
1499996      441377       453297      153085    289573      117668   
1499997      441377       453297      153085    289573      117668   
1499998      441377       453297      153085    289573      117668   
1499999        4145         4434      153085    289573      117668   

         CountryCode  hour  day  month  weekday   IncidentGrade  
0                242    14   13      6        3   FalsePositive  
1                242    19   12      6        2    TruePositive  
2                242    19    6      6        3  BenignPositive  
3                242    23    2      6        6    TruePositive  
4                242     1   12      6        2    TruePositive  
...              ...   ...  ...    ...      ...             ...  
1499995          242    16    5      6        2    TruePositive  
1499996          242    10    7      6        4  BenignPositive  
1499997            1    10    7      6        4    TruePositive  
1499998           17    16   11      6        1   FalsePositive  
1499999          242     0    8      6        5    TruePositive  

[1500000 rows x 16 columns]

In [13]:
from sklearn.preprocessing import LabelEncoder 

le=LabelEncoder() 

dft2["IncidentGrade"]=le.fit_transform(dft2["IncidentGrade"])
dft2.head()

Category        EntityType  DeviceId  IpAddress     Url  \
0       InitialAccess              User     98799     360606  160396   
1    CredentialAccess              User     98799     360606  160396   
2        Exfiltration       MailMessage     98799     360606  160396   
3  SuspiciousActivity           Machine        21     360606  160396   
4    CredentialAccess  CloudApplication     98799     360606  160396   

   AccountSid  AccountName  DeviceName  FileName  FolderPath  CountryCode  \
0       12578        13834      153085    289573      117668          242   
1      145718       139254      153085    289573      117668          242   
2      441377       453297      153085    289573      117668          242   
3      441377       453297          26    289573      117668          242   
4      441377       453297      153085    289573      117668          242   

   hour  day  month  weekday  IncidentGrade  
0    14   13      6        3              1  
1    19   12      6        2              2  
2    19    6      6        3              0  
3    23    2      6        6              2  
4     1   12      6        2              2

In [15]:
                                  #TARGET ENCODING

import pandas as pd
from sklearn.model_selection import train_test_split 

X = dft2[["Category"]]  
y = dft2["IncidentGrade"]  

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train_combined = pd.concat([X_train, y_train], axis=1)

category_mean = X_train_combined.groupby('Category')['IncidentGrade'].mean()

dft2['Category'] = dft2['Category'].map(category_mean).round(3)

dft2.head()

Category        EntityType  DeviceId  IpAddress     Url  AccountSid  \
0     1.300              User     98799     360606  160396       12578   
1     1.038              User     98799     360606  160396      145718   
2     0.511       MailMessage     98799     360606  160396      441377   
3     0.947           Machine        21     360606  160396      441377   
4     1.038  CloudApplication     98799     360606  160396      441377   

   AccountName  DeviceName  FileName  FolderPath  CountryCode  hour  day  \
0        13834      153085    289573      117668          242    14   13   
1       139254      153085    289573      117668          242    19   12   
2       453297      153085    289573      117668          242    19    6   
3       453297          26    289573      117668          242    23    2   
4       453297      153085    289573      117668          242     1   12   

   month  weekday  IncidentGrade  
0      6        3              1  
1      6        2              2  
2      6        3              0  
3      6        6              2  
4      6        2              2

In [17]:
import pandas as pd
from sklearn.model_selection import train_test_split 

X = dft2[["EntityType"]]  
y = dft2["IncidentGrade"]  

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train_combined = pd.concat([X_train, y_train], axis=1)

category_mean = X_train_combined.groupby('EntityType')['IncidentGrade'].mean()

dft2['EntityType'] = dft2['EntityType'].map(category_mean).round(3)

dft2.head()

Category  EntityType  DeviceId  IpAddress     Url  AccountSid  AccountName  \
0     1.300       1.101     98799     360606  160396       12578        13834   
1     1.038       1.101     98799     360606  160396      145718       139254   
2     0.511       0.651     98799     360606  160396      441377       453297   
3     0.947       0.710        21     360606  160396      441377       453297   
4     1.038       1.011     98799     360606  160396      441377       453297   

   DeviceName  FileName  FolderPath  CountryCode  hour  day  month  weekday  \
0      153085    289573      117668          242    14   13      6        3   
1      153085    289573      117668          242    19   12      6        2   
2      153085    289573      117668          242    19    6      6        3   
3          26    289573      117668          242    23    2      6        6   
4      153085    289573      117668          242     1   12      6        2   

   IncidentGrade  
0              1  
1              2  
2              0  
3              2  
4              2

In [35]:
                                                   TARGET ENCODING FOR CATEGORICAL COLUMNS

import pandas as pd


columns_to_encode = ['DeviceId', 'IpAddress', 'Url', 'AccountSid', 'AccountName', 'DeviceName', 'FileName', 'FolderPath', 'CountryCode']


for column in columns_to_encode:
    column_mean = dft2.groupby(column)['IncidentGrade'].mean()
    
    
    dft2[column] = dft2[column].map(column_mean).round(3)


dft2.head()

Category  EntityType  DeviceId  IpAddress    Url  AccountSid  AccountName  \
0     1.300       1.101     1.012      0.942  1.018       1.000        1.000   
1     1.038       1.101     1.012      0.942  1.018       2.000        2.000   
2     0.511       0.651     1.012      0.942  1.018       0.971        0.979   
3     0.947       0.710     2.000      0.942  1.018       0.971        0.979   
4     1.038       1.011     1.012      0.942  1.018       0.971        0.979   

   DeviceName  FileName  FolderPath  CountryCode  hour  day  month  weekday  \
0       1.025     1.043       1.039        0.934    14   13      6        3   
1       1.025     1.043       1.039        0.934    19   12      6        2   
2       1.025     1.043       1.039        0.934    19    6      6        3   
3       2.000     1.043       1.039        0.934    23    2      6        6   
4       1.025     1.043       1.039        0.934     1   12      6        2   

   IncidentGrade  
0              1  
1              2  
2              0  
3              2  
4              2

In [98]:
import pandas as pd 


columns_to_encode= ['hour', 'day', 'month', 'weekday'] 

for column in columns_to_encode:
     column_mean = dft2.groupby(column)['IncidentGrade'].mean()
     
     
     dft2[column]=dft2[column].map(column_mean).round(3) 


dft2.head()


Category  EntityType  DeviceId  IpAddress    Url  AccountSid  AccountName  \
0     1.300       1.101     1.012      0.942  1.018       1.000        1.000   
1     1.038       1.101     1.012      0.942  1.018       2.000        2.000   
2     0.511       0.651     1.012      0.942  1.018       0.971        0.979   
3     0.947       0.710     2.000      0.942  1.018       0.971        0.979   
4     1.038       1.011     1.012      0.942  1.018       0.971        0.979   

   DeviceName  FileName  FolderPath  CountryCode   hour    day  month  \
0       1.025     1.043       1.039        0.934  0.941  0.852  1.001   
1       1.025     1.043       1.039        0.934  0.954  0.843  1.001   
2       1.025     1.043       1.039        0.934  0.954  0.958  1.001   
3       2.000     1.043       1.039        0.934  1.009  1.051  1.001   
4       1.025     1.043       1.039        0.934  1.044  0.843  1.001   

   weekday  IncidentGrade  
0    0.910              1  
1    0.988              2  
2    0.910              0  
3    1.121              2  
4    0.988              2

In [112]:
dft2.to_csv("dft2.csv",index=False)

In [1]:
import pandas as pd 

dft3=pd.read_csv("dft2.csv") 
dft3.head()

Category  EntityType  DeviceId  IpAddress    Url  AccountSid  AccountName  \
0     1.300       1.101     1.012      0.942  1.018       1.000        1.000   
1     1.038       1.101     1.012      0.942  1.018       2.000        2.000   
2     0.511       0.651     1.012      0.942  1.018       0.971        0.979   
3     0.947       0.710     2.000      0.942  1.018       0.971        0.979   
4     1.038       1.011     1.012      0.942  1.018       0.971        0.979   

   DeviceName  FileName  FolderPath  CountryCode   hour    day  month  \
0       1.025     1.043       1.039        0.934  0.941  0.852  1.001   
1       1.025     1.043       1.039        0.934  0.954  0.843  1.001   
2       1.025     1.043       1.039        0.934  0.954  0.958  1.001   
3       2.000     1.043       1.039        0.934  1.009  1.051  1.001   
4       1.025     1.043       1.039        0.934  1.044  0.843  1.001   

   weekday  IncidentGrade  
0    0.910              1  
1    0.988              2  
2    0.910              0  
3    1.121              2  
4    0.988              2

In [ ]:
                                       #DECISION TREE

In [3]:
                               #TRIAL AND ERROR METHOD TO FIND BEST MAX_DEPTH 

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report  



X=dft3.drop(columns=["IncidentGrade"]) 
y=dft3["IncidentGrade"] 

X_train,X_val,y_train,y_val=train_test_split(X,y,test_size=0.2,random_state=42) 

max_depth_values = [5, 10, 15, 20]
min_samples_split_values = [2, 5, 10]
min_samples_leaf_values = [1, 2, 5]
criterion_values = ['gini', 'entropy'] 

best_accuracy=0 
best_params={} 

for max_depth in max_depth_values:
    for min_samples_split in min_samples_split_values:
        for min_samples_leaf in min_samples_leaf_values:
            for criterion in criterion_values:
                clf=DecisionTreeClassifier(max_depth=max_depth,
                                           min_samples_split=min_samples_split,
                                           min_samples_leaf=min_samples_leaf,
                                           criterion=criterion,
                                           random_state=42) 
                clf.fit(X_train,y_train)
                y_pred=clf.predict(X_val) 
                accuracy=accuracy_score(y_pred,y_val) 
                if accuracy>best_accuracy:
                    best_accuracy=accuracy
                    best_params={
                        'max_depth':max_depth,
                        'min_samples_split':min_samples_split,
                        'min_samples_leaf':min_samples_leaf,
                        'criterion':criterion 
                    } 

print("Best Accuracy:",best_accuracy) 
print("Best_params:",best_params)


Best Accuracy: 0.8206433333333333
Best_params: {'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 1, 'criterion': 'gini'}


In [5]:
                                    #DECISION TREE CLASSIFICATION 

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report 

X=dft3.drop(columns=["IncidentGrade"]) 
y=dft3["IncidentGrade"]  

X_train,X_val,y_train,y_val=train_test_split(X,y,test_size=0.3,random_state=42) 


model_tree=DecisionTreeClassifier(max_depth=20,random_state=42) 


model_tree.fit(X_train,y_train) 

y_pred=model_tree.predict(X_val) 

print("Accuracy: ", accuracy_score(y_val, y_pred))
print("Confusion Matrix: \n", confusion_matrix(y_val, y_pred))
print("Classification Report: \n", classification_report(y_val, y_pred))


Accuracy:  0.8211688888888888
Confusion Matrix: 
 [[126700  20818   2289]
 [ 20162 121422   8380]
 [ 14309  14516 121404]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.79      0.85      0.81    149807
           1       0.77      0.81      0.79    149964
           2       0.92      0.81      0.86    150229

    accuracy                           0.82    450000
   macro avg       0.83      0.82      0.82    450000
weighted avg       0.83      0.82      0.82    450000



In [13]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.tree import DecisionTreeClassifier
import numpy as np

param_dist = {
    'max_depth': [5, 10, 20],  
    'min_samples_split': [2, 5, 10],     
    'min_samples_leaf': [1, 2, 5],       
    'criterion': ['gini', 'entropy'],   
    'max_features': [None, 'sqrt', 'log2'],
    'splitter': ['best', 'random']      
}

random_search = RandomizedSearchCV(estimator=model_tree,param_distributions=param_dist, n_iter=10, cv=3, scoring='accuracy', n_jobs=-1, random_state=42, verbose=1)

random_search.fit(X_train, y_train)

print("Best Hyperparameters:", random_search.best_params_)
print("Best Accuracy from RandomizedSearchCV:", random_search.best_score_)

best_tree = random_search.best_estimator_
y_pred = best_tree.predict(X_val)


print("Test Accuracy: ", accuracy_score(y_val, y_pred))
print("Confusion Matrix: \n", confusion_matrix(y_val, y_pred))
print("Classification Report: \n", classification_report(y_val, y_pred))

Fitting 3 folds for each of 10 candidates, totalling 30 fits
Best Hyperparameters: {'splitter': 'best', 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': None, 'max_depth': 20, 'criterion': 'gini'}
Best Accuracy from RandomizedSearchCV: 0.8190447619047618
Test Accuracy:  0.8211688888888888
Confusion Matrix: 
 [[126700  20818   2289]
 [ 20162 121422   8380]
 [ 14309  14516 121404]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.79      0.85      0.81    149807
           1       0.77      0.81      0.79    149964
           2       0.92      0.81      0.86    150229

    accuracy                           0.82    450000
   macro avg       0.83      0.82      0.82    450000
weighted avg       0.83      0.82      0.82    450000



In [17]:
train_predictions = best_tree.predict(X_train)
validation_predictions = best_tree.predict(X_val)

train_accuracy = accuracy_score(y_train, train_predictions)
validation_accuracy = accuracy_score(y_val, validation_predictions)

print(f"Training Accuracy: {train_accuracy}")
print(f"Validation Accuracy: {validation_accuracy}")

Training Accuracy: 0.8292542857142857
Validation Accuracy: 0.8211688888888888


In [19]:
import joblib 
joblib.dump(best_tree,'best_decision_tree.pkl')

['best_decision_tree.pkl']

In [ ]:
                                       #RANDOM FOREST CLASSIFICATION

In [5]:
                                            #TRIAL AND ERROR METHOD

from sklearn.ensemble import RandomForestClassifier 
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report 
from sklearn.model_selection import train_test_split

X=dft3.drop(columns=["IncidentGrade"]) 
y=dft3["IncidentGrade"]  

X_train,X_val,y_train,y_val=train_test_split(X,y,test_size=0.3,random_state=42) 

n_estimators_values = [100, 200] 

results={} 

for n in n_estimators_values:
    rf_model=RandomForestClassifier(n_estimators=n,random_state=42) 
    rf_model.fit(X_train,y_train)
    y_pred=rf_model.predict(X_val) 
    accuracy=accuracy_score(y_val,y_pred) 
    results[n]=accuracy
    print(f"Accuracy for n_estimators={n}: {accuracy * 100:.2f}")  

best_n_estimators = max(results, key=results.get)
print(f"Best n_estimators value: {best_n_estimators}")


Accuracy for n_estimators=100: 84.89
Accuracy for n_estimators=200: 84.88
Best n_estimators value: 100


In [3]:
                                    #RANDOMFORESTCLASSIFICATION


from sklearn.ensemble import RandomForestClassifier 
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report 
from sklearn.model_selection import train_test_split

X=dft3.drop(columns=["IncidentGrade"]) 
y=dft3["IncidentGrade"]  

X_train,X_val,y_train,y_val=train_test_split(X,y,test_size=0.3,random_state=42) 


model_rf=RandomForestClassifier(n_estimators=100, random_state=42) 

model_rf.fit(X_train,y_train)

y_pred=model_rf.predict(X_val) 

print("Accuracy: ", accuracy_score(y_val, y_pred))
print("Confusion Matrix: \n", confusion_matrix(y_val, y_pred))
print("Classification Report: \n", classification_report(y_val, y_pred))


Accuracy:  0.8488955555555555
Confusion Matrix: 
 [[131058  12271   6478]
 [ 16617 121654  11693]
 [ 11154   9784 129291]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.83      0.87      0.85    149807
           1       0.85      0.81      0.83    149964
           2       0.88      0.86      0.87    150229

    accuracy                           0.85    450000
   macro avg       0.85      0.85      0.85    450000
weighted avg       0.85      0.85      0.85    450000



In [5]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import numpy as np

param_dist = {
    'max_depth': [None, 10, 20],  
    'min_samples_split': [2, 5], 
    'min_samples_leaf': [1, 2],    
    'max_features': ['sqrt', 'log2']  
}
random_search = RandomizedSearchCV(estimator=model_rf, param_distributions=param_dist, 
                                   n_iter=5, scoring='accuracy', cv=2, verbose=2, n_jobs=-1, random_state=42)

random_search.fit(X_train, y_train)

print(f"Best hyperparameters: {random_search.best_params_}")

best_rf_model = random_search.best_estimator_

y_pred_best = best_rf_model.predict(X_val)

print(f"Final Model Test Accuracy: {accuracy_score(y_val, y_pred_best)}")
print("Confusion Matrix: \n", confusion_matrix(y_val, y_pred_best))
print("Classification Report: \n", classification_report(y_val, y_pred_best))

Fitting 2 folds for each of 5 candidates, totalling 10 fits
Best hyperparameters: {'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': None}
Final Model Test Accuracy: 0.8488955555555555
Confusion Matrix: 
 [[131058  12271   6478]
 [ 16617 121654  11693]
 [ 11154   9784 129291]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.83      0.87      0.85    149807
           1       0.85      0.81      0.83    149964
           2       0.88      0.86      0.87    150229

    accuracy                           0.85    450000
   macro avg       0.85      0.85      0.85    450000
weighted avg       0.85      0.85      0.85    450000



In [7]:
train_predictions = best_rf_model.predict(X_train)
validation_predictions = best_rf_model.predict(X_val)

train_accuracy = accuracy_score(y_train, train_predictions)
validation_accuracy = accuracy_score(y_val, validation_predictions)

print(f"Training Accuracy: {train_accuracy}")
print(f"Validation Accuracy: {validation_accuracy}")

Training Accuracy: 0.883127619047619
Validation Accuracy: 0.8488955555555555


In [9]:
import joblib 
joblib.dump(best_rf_model,'best_model_rf.pkl')

['best_model_rf.pkl']

In [ ]:
                                               XG BOOST

In [3]:
!pip install xgboost

In [5]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score 

X=dft3.drop(columns=["IncidentGrade"]) 
y=dft3["IncidentGrade"]  

X_train,X_val,y_train,y_val=train_test_split(X,y,test_size=0.2,random_state=42) 

model1 = xgb.XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, subsample=0.8, colsample_bytree=0.8)
model1.fit(X_train, y_train)
y_pred1 = model1.predict(X_val)
accuracy1 = accuracy_score(y_val, y_pred1)
print(f"Trial 1 Accuracy: {accuracy1}")

model2 = xgb.XGBClassifier(n_estimators=200, learning_rate=0.05, max_depth=5, subsample=0.9, colsample_bytree=0.9)
model2.fit(X_train, y_train)
y_pred2 = model2.predict(X_val)
accuracy2 = accuracy_score(y_val, y_pred2)
print(f"Trial 2 Accuracy: {accuracy2}")

model3 = xgb.XGBClassifier(n_estimators=300, learning_rate=0.01, max_depth=7, subsample=1.0, colsample_bytree=1.0)
model3.fit(X_train, y_train)
y_pred3 = model3.predict(X_val)
accuracy3 = accuracy_score(y_val, y_pred3)
print(f"Trial 3 Accuracy: {accuracy3}")



Trial 1 Accuracy: 0.80941
Trial 2 Accuracy: 0.82205
Trial 3 Accuracy: 0.8136766666666667


In [7]:
                                                   #XG BOOST

import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report  

X=dft3.drop(columns=["IncidentGrade"]) 
y=dft3["IncidentGrade"]  

X_train,X_val,y_train,y_val=train_test_split(X,y,test_size=0.2,random_state=42) 


model_xgb=xgb.XGBClassifier(n_estimators=200, learning_rate=0.05, max_depth=5, subsample=0.9, colsample_bytree=0.9) 

model_xgb.fit(X_train,y_train) 

y_pred=model_xgb.predict(X_val) 

print("Accuracy Score:",accuracy_score(y_val,y_pred)) 
print("Classification report: \n",classification_report(y_val,y_pred)) 
print("Confusion Matrix: \n",confusion_matrix(y_val,y_pred))



Accuracy Score: 0.82205
Classification report: 
               precision    recall  f1-score   support

           0       0.77      0.88      0.82     99937
           1       0.80      0.77      0.79     99958
           2       0.91      0.82      0.86    100105

    accuracy                           0.82    300000
   macro avg       0.83      0.82      0.82    300000
weighted avg       0.83      0.82      0.82    300000

Confusion Matrix: 
 [[87723 10340  1874]
 [16069 77302  6587]
 [ 9500  9015 81590]]


In [ ]:
                                               ADA-BOOST

In [17]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


X=dft3.drop(columns=["IncidentGrade"]) 
y=dft3["IncidentGrade"]  

X_train,X_val,y_train,y_val=train_test_split(X,y,test_size=0.2,random_state=42) 

model1 = AdaBoostClassifier(n_estimators=100, learning_rate=0.01, random_state=42,algorithm='SAMME')
model1.fit(X_train, y_train)
y_pred1 = model1.predict(X_val)
accuracy1 = accuracy_score(y_val, y_pred1)
print(f"Trial 1 Accuracy: {accuracy1}")

model2 = AdaBoostClassifier(n_estimators=200, learning_rate=0.1, random_state=42,algorithm='SAMME')
model2.fit(X_train, y_train)
y_pred2 = model2.predict(X_val)
accuracy2 = accuracy_score(y_val, y_pred2)
print(f"Trial 2 Accuracy: {accuracy2}")

model3 = AdaBoostClassifier(n_estimators=300, learning_rate=0.5, random_state=42,algorithm='SAMME')
model3.fit(X_train, y_train)
y_pred3 = model3.predict(X_val)
accuracy3 = accuracy_score(y_val, y_pred3)
print(f"Trial 3 Accuracy: {accuracy3}")


Trial 1 Accuracy: 0.4224233333333333
Trial 2 Accuracy: 0.6261166666666667
Trial 3 Accuracy: 0.7681766666666666


In [21]:
                                         #ADA BOOST

from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report  

X=dft3.drop(columns=["IncidentGrade"]) 
y=dft3["IncidentGrade"]  

X_train,X_val,y_train,y_val=train_test_split(X,y,test_size=0.2,random_state=42) 


model_ad=AdaBoostClassifier(n_estimators=300,learning_rate=0.5,random_state=42,algorithm='SAMME')

model_ad.fit(X_train,y_train) 

y_pred=model_ad.predict(X_val) 

print("Classification report: \n",classification_report(y_val,y_pred)) 
print("Confusion Matrix: \n",confusion_matrix(y_val,y_pred))


Classification report: 
               precision    recall  f1-score   support

           0       0.98      0.61      0.75     99937
           1       0.61      0.89      0.72     99958
           2       0.88      0.80      0.84    100105

    accuracy                           0.77    300000
   macro avg       0.82      0.77      0.77    300000
weighted avg       0.82      0.77      0.77    300000

Confusion Matrix: 
 [[61449 37601   887]
 [ 1056 89268  9634]
 [  407 19962 79736]]


In [ ]:
Comparison and Analysis:
Accuracy:
Random Forest has the highest accuracy (0.85), followed by Decision Tree (0.82) and XGBoost (0.82).

Precision, Recall, and F1-Score:
Random Forest also outperforms the others in the macro average precision, recall, and F1-score with values around 0.85 for all metrics.
Decision Tree and XGBoost are more similar in performance, with a macro average around 0.82–0.83, which is lower than Random Forest.

Confusion Matrix:
Random Forest does a better job of correctly classifying Class 0 and Class 2. It has higher precision and recall for these classes compared to the other two models.
XGBoost performs well for Class 2, but struggles more with Class 0 and Class 1 compared to Random Forest.
Decision Tree performs decently with Class 2, but its performance for Class 0 and Class 1 is worse than both Random Forest and XGBoost.

Conclusion:
Based on the accuracy score, classification report, and confusion matrix, the Random Forest model is the best among the three. It has the highest accuracy and overall better performance across all metrics.

Since Random Forest seems to be the best model, it would be the ideal candidate for hyperparameter tuning to further improve its performance.